### ISSUE TITLE
href option is not working

### ISSUE THREAD

**Issue by jonas-budde** [timvink/mkdocs-git-authors-plugin#112]
Hello,

i have defined the following config in my mkdocs.yaml file:

```yaml
  - git-authors:
      add_co_authors: true
      show_email_address: true
      href: "https://github.com/{name}"
      exclude:
      - index.md
```

The href isn't referencing my github profile. Have I forgotten something or done something wrong?
I'm also not able to change to a new mail reference with e.g. - href: "https://teams.microsoft.com/l/chat/0/0?users={email}"
