### ISSUE TITLE
Upgrade unit tests with more git versions

### ISSUE THREAD

**Issue by timvink** [timvink/mkdocs-git-authors-plugin#17]
This plugins relies on retrieving information from git commands (`git blame`). 

Currently we test:

```yml
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
```

To improve the unit tests we can upgrade our github workflow and test on older OS and with different versions of GIT.
