### ISSUE TITLE
Inconsistent between environments

### ISSUE THREAD

**Issue by bserem** [timvink/mkdocs-git-authors-plugin#44]
I added the plugin and it worked flawlessly locally, using both `mkdocs serve` and `mkdocs build`.
I added the Jinja tags in my template files (I use material theme) and all was good, including the extra options.

Then I pushed my changes to the remote repository, the build system triggered itself and pushed the updated documentation. There, all attribution names were meshed up. Different authors were being assigned to every page and different totals (`{{ git_site_authors }}`) were being calculated.

I can't provide the means to reproduce the issue, because I do not know them yet, but I can provide my pipeline:
```
image: squidfunk/mkdocs-material

options:
    docker: true

pipelines:
  branches:
    master:
      - step:
          name: 'Deploy docs'
          caches:
            - docker
            - pip
          script:
            - pip3 install mkdocs-awesome-pages-plugin
            - pip3 install mkdocs-git-revision-date-plugin
            - pip3 install mkdocs-git-authors-plugin
            - mkdocs --version
            - mkdocs -v build
            - pipe: atlassian/rsync-deploy:0.2.0
              variables:
                USER: 'SOME_USER'
                SERVER: 'SOME_SERVER'
                REMOTE_PATH: '/SOME_FOLDER/'
                LOCAL_PATH: 'site'
```
and my mkdocs.yml (sensitive info removed):
```
# Project Info
site_name: -
side_description: -
site_url: '-'

# Repository
repo_name: 'SOME_REPO'
repo_url: 'https://bitbucket.org/SOME_REPO'
edit_uri: 'src/master/docs'

# Copyright
copyright: 'Copyright &copy; 2019-2020'

theme:
  name: 'material'
  palette:
    primary: 'light green'
    accent: 'deep purple'
  favicon: assets/favicon.ico
  custom_dir: 'material'
  feature:
    tabs: true
  logo: assets/logo.svg
  extra:
    manifest: 'manifest.webmanifest'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta

plugins:
  - search
  - awesome-pages
  - git-revision-date
  - git-authors:
      show-contribution: true
```

**Comment by timvink** [comment]
Hi @bserem ,

Build systems often do what's called a shallow git clone. This retrieves only the latest commit instead of the full commit history, which is efficient when building because you only need the latest source code.

In this case however, we *do* need the full commit history, in order to be able to use `git blame` to know who committed which line.

For this plugin I still need to document this behaviour and the fix, which is to [change the settings of your build systems](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin#note-when-using-on-ci-runners).

Let me know if that fixes it for you (there might be a second problem going on..). Let's leave this issue open until:

- The README contains instructions
- Automatic warnings on build systems are generated (just like `mkdocs-git-revision-date-localized-plugin`)

**Comment by bserem** [comment]
@timvink thanks for the heads up! I had no idea about the fact that build systems only fetch the last commit. Bitbucket by default actually fetches the last 5 commits, which made the results even more confusing.

The documentation for Bitbucket is located here:
https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/ (search for depth)
and the pipeline file should be like this:
```
clone:
  depth: full
  
pipelines:
  default:
    - step:
        name: Cloning
        script:
          - echo "Clone all the things!"
```

This can be closed as far as I am concerned.
I am not using you revision date plugin yet, I still use `mkdocs-git-revision-date-plugin` so I missed the instructions there.
So, like you said, there is no issue with the plugin, it is merely a configuration issue in the build task.

Thanks
