### ISSUE TITLE
Disable on Preview

### ISSUE THREAD

**Issue by skalde** [timvink/mkdocs-git-authors-plugin#46]
We are using your plugin in our CI system and the local preview.
unfortunately it slows down the preview on saving a file.

some plugins used an `enabled_if_env:` entry to disable it, except on CI pipelines.

it would be nice to have this feature on your plugin too

```yaml
plugins:
  - git-revision-date:
      enabled_if_env: CI
  - git-authors:
      show_contribution: true
      show_line_count: true
      enabled_if_env: CI
```
