### ISSUE TITLE
Exclude author from pages

### ISSUE THREAD

**Issue by CaloC-NZ** [timvink/mkdocs-git-authors-plugin#55]
Sorry if this was asked before, I could not find anything in the issues search, was wondering if its possible to exclude the author from certain pages, similar to the git-revision-date-localized plugin?

``` yml
  - git-revision-date-localized: # https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/
      type: date
      timezone: Pacific/Auckland
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
        - index.md
        - tags.md
```

Great plugins btw.
