### ISSUE TITLE
Authorship_threshold_percent ignored

### ISSUE THREAD

**Issue by christophhillisch** [timvink/mkdocs-git-authors-plugin#72]
I am running into the problem that configurations beyond the first one (`show_contribution: true`) are ignored. I set `authorship_threshold_percent: 10`, but I found contributions of 0.88 %.

**Package Versions:**

- mkdocs 1.4.2
- mkdocs-git-authors-plugin 0.7.0 
- mkdocs-git-revision-date-localized-plugin 1.1.0 
- mkdocs-material 9.0.13 
- mkdocs-material-extensions 1.1.1 
- python 1.10

**Relevant parts in mkdocs.yml:**

```
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: false
      timezone: Europe/Paris
  - git-authors:
      show_contribution: true
      sort_authors_by: contribution
      authorship_threshold_percent: 10
```
